### ISSUE TITLE
Cli not getting whole string

### ISSUE THREAD

**Issue by vforv** [hemerajs/hemera-cli#3]
Hi,

I have one problem with actions from hemera cli:

act --pattern topic:jwt,cmd:generate,userId:59b6f0c2fa4253406099ad06

userId part does not send whole string just first 2 numbers: 59

**Comment by StarpTech** [comment]
Thanks for reporting. This is an issue in the tinysonic module. I created a PR https://github.com/mcollina/tinysonic/pull/3/files to fix it.

**Comment by StarpTech** [comment]
Please reinstall the package. It was fixed with release hemera@1.5.13

**Comment by vforv** [comment]
It works now, thanks.
